### ISSUE TITLE
Missing "Pods" folder

### ISSUE THREAD

**Issue by wellkunnected** [TalkingBibles/Talking-Bible-iOS#1]
Hi,

The app won't build without the pods folder. Installing cocoapods doesn't work anymore it requires the actual pods folder. Please include if you can, thanks for your help!

**Comment by stphnclysmth** [comment]
Hi, @wellkunnected 

We have discontinued work on the Talking Bible app. The source code was made available for organizational partners, but we will not be maintaining the project into the future. It was merely a wrapper for our recordings, which are hosted separately—without those, the app is pretty useless except as an example.

I will probably add a note to the README to that effect.
